ktor:
    development: true
    application:
        modules:
            - com.github.devinkadrie.basedbin.ApplicationKt.module
    deployment:
        port: 8080
        watch:
            - classes