ktor:
    development: true
    application:
        modules:
            - com.github.devinkadrie.basedbin.ApplicationKt.module
    deployment:
        port: 8080
        watch:
            - classes
postgres:
    url:
        "jdbc:postgresql://localhost:5432/postgres"
    user:
        "postgres"
    password:
        ""